spring: 
  # DB設定
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  # DB初期化
  sql:
    init:
      encoding: UTF-8
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  # H2設定
  h2:
    console:
      enabled: true
  # Messageプロパティ
  messages:
    basename: messages,ValidationMessages
  # JPA
  jpa:
    hibernate:
      ddl-auto: none

# MyBatis
mybatis:
  mapper-locations: classpath*:/mapper/h2/*.xml
  type-aliases-package: com.example.demo.*
  configuration:
    map-underscore-to-camel-case: true

# Log Level
logging:
  level:
    '[com.example.demo]': debug
    # JPAのログ出力
    '[org.hibernate]':
      SQL: debug
      type:
        '[descriptor.sql.BasicBinder]': trace
        EnumType: trace

# Tomcat設定
server:
  servlet:
    session:
      timeout: 30m